# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/REPO
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install && npm install firebase-tools 
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Gatsby Build
          command: npm run build

      - run: npm install firebase-tools 
      # - run: firebase deploy --token "$FIREBASE_TOKEN"  
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy -project creativenation-a5cbc